### ISSUE TITLE
Can not get macros to work for players.

### ISSUE THREAD

**Issue by dyenrac** [DFreds/dfreds-convenient-effects#193] opened 2022-11-26 00:17 UTC
Can not get  macros to work for players.

For example after dragging the candle to the macro bar it works for the GM but not for players.

**Comment by DFreds** [comment] 2022-11-29 22:07
So, you dragged the candle to the macro bar as the GM and then it doesn't work when a player uses that macro? Or the player is unable to drag the candle to the macro bar and have it work?

**Comment by DFreds** [comment] 2022-11-29 22:09
Both seem to work for me

**Comment by dyenrac** [comment] 2022-12-11 00:18
Sorry for the late reply I've been down sick.

I'm running at D&D 5e game through Foundry version 10. I can pull the icon in tot eh macro bar and they function as intended as the GM but nothing happens when I click on the icon as a player.

________________________________

**Comment by dyenrac** [comment] 2022-12-11 00:19
I place the macros in the  players macro tray as the gm
________________________________

**Comment by DFreds** [comment] 2022-12-14 00:05
> I place the macros in the players macro tray as the gm

I'm not sure what you mean by this exactly. How are you placing the macros in the players macro tray as the GM? 

My best guess is that this is a permission issue of some sort. What is the permission level for the players on the macro?

Closing this issues as unable to reproduce for now

**Closed by DFreds** 2022-12-14 00:05 UTC
Labels: bug
