### ISSUE TITLE
Problem with lightsources

### ISSUE THREAD

**Issue by MSAbaddon** [DFreds/dfreds-convenient-effects#31] opened 2021-08-11 22:34 UTC
When I try to add one of the light effects (e.g. Torch) I get the following error message:
![image](https://user-images.githubusercontent.com/66370966/129112311-fa95a58e-d60f-4dbf-8486-0b4a6cdb412d.png)

**Comment by DFreds** [comment] 2021-08-11 23:15
Hm, something must have changed with a dependency as I just tested this. Are you on all of the latest versions of modules?

**Comment by MSAbaddon** [comment] 2021-08-11 23:34
Foundry 0.8.8
DnD 1.4.1
DFreds 1.8.3

**Comment by MSAbaddon** [comment] 2021-08-11 23:35
![image](https://user-images.githubusercontent.com/66370966/129116847-4c766965-132f-4346-b97c-e391024c1e5f.png)

**Comment by DFreds** [comment] 2021-08-12 04:42
I am unable to reproduce this issue. The torch, lantern, and candle effects all work as intended for me. Are you on the latest ATL? Can you provide some detail on other modules you have installed? Find the Culprit is a module which might be helpful if it is an issue with something else.

**Comment by MSAbaddon** [comment] 2021-08-12 13:00
Hi there. Just checked it again with only the actually needed modules active.
The error still occurs.
I'm running Foundry on The Forge - maybe that's an issue?
![image](https://user-images.githubusercontent.com/66370966/129200936-536c1812-b5f6-450e-b302-098bf986903d.png)

**Comment by DFreds** [comment] 2021-08-12 13:46
Very strange. It could be the Forge, but that seems unlikely. I assume it is related to this (https://github.com/kandashi/Active-Token-Lighting/issues/60)

But I don't know why it is happening for you and not me. I tested it both locally and on my hosted instance. Can you try testing it locally as well?

**Comment by DFreds** [comment] 2021-08-12 22:03
Another thought occurred to me. How long have you had active token lighting installed? Because the presets I'm using are stored in a hidden config value, it's possible that ATL changed a bit but your old preset values are now incorrect.

In any case, I think this should be fixed now in v1.8.4 as I stopped using the built in presets. Let me know if it isn't and we can reopen it.

**Closed by DFreds** 2021-08-12 22:03 UTC
Labels: bug

**Comment by MSAbaddon** [comment] 2021-08-13 06:32
You were correct with your guess. I created an item with one of the ATL.preset - as soon as I activate the effect I get the error message. I opened an issue for ATL.

**Comment by MSAbaddon** [comment] 2021-08-13 10:02
Got an answer from Kandashi that solved the issue even with presets:

Go into the preset menu, open torch and then save. That should fix it
