### ISSUE TITLE
Player can't create custom effects, even with the option checked

### ISSUE THREAD

**Issue by SirGarhi** [DFreds/dfreds-convenient-effects#206] opened 2023-01-02 20:24 UTC
**Describe the bug**
Despite having the checkbox enabled, as a player I still get the permissions error when trying to create an effect. Furthermore, each time I try it creates a visible "Custom Convenient Effects" item in the items list.

Note that I can't reproduce this on my local foundry, even as a player account. It's happening in one of the games I'm exclusively a player in. My only thought is that the first effects I created on my local foundry were done as a GM, and in the other game I as a player was the first one to try and create a custom effect. If it matters foundry is configured to allow players to create items in this game.

**To Reproduce**
1. Check the box to enable both the app control to add effects and for players to create effects
2. As a player, open the app control and hit either the Import Custom Effects or Create Effect buttons
3. See error
4. Check the items panel to see the new custom convenient effects item

**Expected behavior**
Player properly creates a new effect and the Custom Convenient Effects item is hidden from the item list

**Screenshots**
![MultipleCustomEffects](https://user-images.githubusercontent.com/113884133/210275106-72c91441-7edd-4b98-8ec6-67581a4b7c70.PNG)

**Additional context**
Again, everything works as expected in my local world, and the only thing I can think of that's different is that it wasn't the GM that tried to create the very first effect in the world where the error is occurring.

**Comment by SirGarhi** [comment] 2023-01-05 03:09
Update, kind of got this working.

DM deleted all the erroneous Custom Convenient Effects, then created a Custom Effect himself.

I was able to see this effect in the list but couldn't edit it and still couldn't make any myself. DM then gave me ownership over the Custom Convenient Effects item that was showing up in the items panel, at which point it disappeared from his view.

After that, I was able to edit the effect already made as well as create my own.

**Comment by DFreds** [comment] 2023-01-20 16:31
This is strange because you shouldn't even be able to see the custom convenient effects item. Were you the first person to ever create a custom one? Might be an edge case around a player being the first one to do it

**Comment by SirGarhi** [comment] 2023-01-20 17:27
Yes I was the first account to try and create a custom effect on that world, as a player.

**Comment by DFreds** [comment] 2023-01-21 00:35
Yeah, I can reproduce this and am looking into a good way to fix it. Thanks for reporting it!

**Comment by DFreds** [comment] 2023-01-21 20:57
Fixed in v3.2.0

**Closed by DFreds** 2023-01-21 20:57 UTC
Labels: bug
