### ISSUE TITLE
Effect Start Time is not set or wrongly set

### ISSUE THREAD

**Issue by FurtherV** [DFreds/dfreds-convenient-effects#273] opened 2023-07-24 19:05 UTC
**Describe the bug**
The `Effect Start Time` upon applying a convenient effect is the `game.time.worldTime` when **the webpage is first loaded** instead of when the effect is applied. This results in effects being applied later to have the wrong duration.

For example, at `worldTime=1` apply the Torch CE. Then advance time by 3600 seconds. Now the effect on the actor has a duration of 0, which is correct since we advanced its entire duration. If we now delete the effect and then apply it again, without reloading the webpage, the duration is again 0 because the `Effect Start Time` of all CE seems to be set upon the webpage load.

**To Reproduce**
1. Apply any effect with a timed duration, like Torch
2. Look at the `Effect Start Time`
3. Advance the World Time
4. Apply any effect with a timed duration, like Torch
5. Look at `Effect Start Time`

**Expected behavior**
Effect Start Time upon application is `game.time.worldTime` from the moment the effect is applied to the actor, not webpage load.

**Additional context**
I only used Convenient Effects, its critical dependencies and nothing else.
No DAE or Times-Up.

**Comment by YenBenGrey** [comment] 2023-07-31 20:32
Hello there, 

As a temporary work around, if you create a custom version of the CE and then go in to the duration of the custom effect and delete the start time, that is a Unix code and save.
The CE works as it is supposed to. 
I know this isn't ideal, but it works for now. :-/

**Comment by MotoMoto1234** [comment] 2023-07-31 20:43
> **Describe the bug** The `Effect Start Time` upon applying a convenient effect is the `game.time.worldTime` when **the webpage is first loaded** instead of when the effect is applied. This results in effects being applied later to have the wrong duration.
> 
> For example, at `worldTime=1` apply the Torch CE. Then advance time by 3600 seconds. Now the effect on the actor has a duration of 0, which is correct since we advanced its entire duration. If we now delete the effect and then apply it again, without reloading the webpage, the duration is again 0 because the `Effect Start Time` of all CE seems to be set upon the webpage load.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Apply any effect with a timed duration, like Torch
> 2. Look at the `Effect Start Time`
> 3. Advance the World Time
> 4. Apply any effect with a timed duration, like Torch
> 5. Look at `Effect Start Time`
> 
> **Expected behavior** Effect Start Time upon application is `game.time.worldTime` from the moment the effect is applied to the actor, not webpage load.
> 
> **Additional context** I only used Convenient Effects, its critical dependencies and nothing else. No DAE or Times-Up.

Are you testing this with just Dfred enabled?  The midi crew have sussed this out to be caused by DAE not dfreds, just making sure we're all looking at the same issue is all.

**Comment by DFreds** [comment] 2023-08-01 15:42
This should be fixed now from #275. Should be in 5.1.0 going out today

**Closed by DFreds** 2023-08-01 15:42 UTC
Labels: bug
