### ISSUE TITLE
Covenient Effects is Adding Multiple of the Same Custom Active Effect

### ISSUE THREAD

**Issue by Shareenx** [DFreds/dfreds-convenient-effects#350] opened 2024-10-29 07:08 UTC
**Module Version:** 7.1.1
**Foundry Version:** 12.331
**Game System** D&D 5E Version 4.0.4
**Effects Panel Version:** 4.02
**Browser:** Chrome Version 129.0.6668.100 (Official Build) (64-bit)
**Other Modules Active:** None

**Describe the bug**
This has been going on for a long time. I had hoped updating to v12, and updating everything would make it go away.
Alas, it is still here.

When a PC Actor (Does not seem to occur for NPC's), multiple custom Active Effects are applied. Just this one, though. "Hurt"
(I have multiple custom effects)
At one point I had DAE, Combat Utility Belt, Active Token Effects some or all going (testing and playing with modules).
I am trying to find where DFred's Convenient Effects reads from to apply the Effects Automatically so I can go in and try to make it stop the multiple applications.

**To Reproduce**
0. Have a Custom Active Effect "Hurt"
0a. At some point, set it in a module somewhere so that it would trigger on HP < 0, to stack multiples.
0b. Go through Module, Foundry, Gaming System updates
0c. Everything is fine, do 0b several more times.
0d. One day-

Open a PC Character Sheet
Click on the Current HP
Type "-5" (or adjust manually to some number lower than the max)
See error

**Expected behavior**
Just one instance of the custom Active Effect "Hurt" to be applied.

**Screenshots**
See below

**Additional context**
I am certain some other module made some change to a config file flagging which Active Effects automatically should be applied. At one point I had DAE, Combat Utility Belt, Active Token Effects some or all going (testing and playing with modules).
However, those modules either are deprecated, do not work, uninstalled, or inactive.
Dfred's is the module applying the Active Effect automatically, so just would like to know where it is reading that from.

**Attachment Descriptions**
**Set HP to 40/ 45**
[Add_Hurt.log](https://github.com/user-attachments/files/17552841/Add_Hurt.log)
<img width="500" alt="1" src="https://github.com/user-attachments/assets/c1667aab-ad7d-4cbb-bb47-25b2f4f6e95c">

Clear log, set HP back to max
[Heal_Up.log](https://github.com/user-attachments/files/17552847/Heal_Up.log)
<img width="474" alt="2" src="https://github.com/user-attachments/assets/a4f70410-9e56-4d26-b4f4-bcba7692692b">

Set name of the Active Effect to something else, Apply damage (Set HP to 40/45)
[Hurt_Effect_Missing.log](https://github.com/user-attachments/files/17552854/Hurt_Effect_Missing.log)

**Pictures of the Active Effect Card**
<img width="289" alt="3" src="https://github.com/user-attachments/assets/85eec1e7-459c-4c39-826d-a04bf75373fe">
<img width="290" alt="4" src="https://github.com/user-attachments/assets/8b00a755-eeac-4aa0-b85f-80722439b556">
<img width="287" alt="image" src="https://github.com/user-attachments/assets/db8e3ee8-6768-427d-bab8-e77312924228">
<img width="286" alt="image" src="https://github.com/user-attachments/assets/b19125c2-2a8d-46a9-8dc3-ac6f36ffd002">

**Comment by DFreds** [comment] 2024-10-30 17:35
To be super clear here, Convenient Effects never applies automatically. There is nothing in the code base that supports any auto apply functionality on changes to an actor. This has to be caused by some other module that is not checking if something is applied first, or something. I really don't have a strong grasp of what you have set up here.

**Comment by Shareenx** [comment] 2024-10-30 19:24
That's the weird thing. 
I *did* do stuff with CUB, or DAE, or other things in the (long) past, but disabled the modules and even uninstalled.
The weirdest thing is that the Dev Console says Dfred's is doing it, automagically. 
Even with *no* other modules active. 
What I ended up doing is disabling the effects in Dfred's (if I delete them, a million errors pop up saying the effect is missing)
What I am trying to figure out is what could be using DFred's to apply effects when nothing else is active. 
It's like something modified a Foundry config somewhere and is sneaky Pete applying stuff. 
Argh, I was hoping you had a clue what could be doing it, because something is using Convenient Effects to do this. Bah!

**Comment by DFreds** [comment] 2024-11-08 19:18
Yeah... It might be embedded in the world data, or in the item flags or who knows what else. If it doesn't occur in a new world, then it has to be because of the old world's data, and that's going to be pretty challenging to find. I'm happy to help (or you can ask on my Discord), but I'm going to close this as an actual CE issue

**Closed by DFreds** 2024-11-08 19:18 UTC
Labels: bug

**Comment by Shareenx** [comment] 2024-12-13 22:46
Just for historic purposes, I found the place this was being pulled from, in case anyone else has the issue:
One or another mod added stuff to "Shift-G"- the "[Global] Mappings panel. - it has added links to Dfred's Convenient Effect Toggles. =D
I removed them, and the behavior went away!
![image](https://github.com/user-attachments/assets/50c74bdf-79d1-4bfa-924b-2a6647206dc5)

**Comment by DFreds** [comment] 2025-01-08 21:21
> Just for historic purposes, I found the place this was being pulled from, in case anyone else has the issue: One or another mod added stuff to "Shift-G"- the "[Global] Mappings panel. - it has added links to Dfred's Convenient Effect Toggles. =D I removed them, and the behavior went away! ![image](https://private-user-images.githubusercontent.com/81126418/395716208-50c74bdf-79d1-4bfa-924b-2a6647206dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNzE1NzIsIm5iZiI6MTczNjM3MTI3MiwicGF0aCI6Ii84MTEyNjQxOC8zOTU3MTYyMDgtNTBjNzRiZGYtNzlkMS00YmZhLTkyNGItMmE2NjQ3MjA2ZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDIxMjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZjYyNGQ3MGVkMjcyNGU3MWQ1OTBhNzMyOWRlOTMxMjQ4MmE3NDU1M2Q5OGZlOWQ3OWU4NGM1MWZmYWRiMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.24NB8NaoAJ7SzN6YtqUeoQxahUyIiG_NlxT4Zen1t4Y)

I appreciate people like you, thanks for the update!
